name: MinGW 8.1.0 CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      shell: cmd
      env:  
        CC: gcc 
        CXX: g++
      run: cmake -S . -B build
        -DCMAKE_BUILD_TYPE=Release
        -GNinja
        -DCMAKE_MAKE_PROGRAM="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe"
    
    - name: build
      shell: cmd
      env:
        NINJA_STATUS: "[%f/%t %o/sec] " 
      run: cmake --build build
      
    - name: test
      shell: cmd
      env:
        CTEST_OUTPUT_ON_FAILURE: ON
      run: cmake --build build --target test
